# Generated by Django 5.0.4 on 2024-05-05 18:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(unique=True)),
                ('mint_address', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('symbol', models.CharField(max_length=250)),
                ('creator', models.CharField(max_length=250, null=True)),
                ('cap', models.FloatField(max_length=250)),
                ('dev_percentage', models.FloatField(default=0)),
                ('bought', models.FloatField(max_length=250)),
                ('created_at', models.DateTimeField(default=api.models.default_datetime)),
            ],
        ),
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_percentage_min', models.FloatField(default=0)),
                ('dev_percentage_max', models.FloatField()),
                ('current_holders', models.IntegerField(default=2)),
                ('capital_coin', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
