# Generated by Django 5.0.4 on 2024-05-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configurations_amount_to_buy_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coininfo',
            table='coin_info',
        ),
        migrations.AlterModelTable(
            name='configurations',
            table='configurations',
        ),
        migrations.AlterModelTable(
            name='portofolio',
            table='portfolio',
        ),
        migrations.AlterModelTable(
            name='tradepair',
            table='trade_pair',
        ),
    ]
