# Generated by Django 5.0.4 on 2024-05-11 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_coininfo_table_alter_configurations_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portofolio',
            name='amount',
        ),
        migrations.AddField(
            model_name='portofolio',
            name='coin_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='execution_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='is_jupiter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='is_pump_fun',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='min_amount_out',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='platform_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='price_impact',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='base_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='trade_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tradepair'),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='txid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
