# Generated by Django 5.0.4 on 2024-05-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_portofolio_amount_portofolio_coin_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='solana_wallet_address',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
