# Generated by Django 5.0.4 on 2024-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_portofolio_base_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="configurations",
            old_name="slippage_rate",
            new_name="buy_slippage_rate",
        ),
        migrations.AddField(
            model_name="configurations",
            name="sell_slippage_rate",
            field=models.FloatField(default=10),
        ),
    ]
