# Generated by Django 5.0.4 on 2024-05-13 21:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_coin_id_portofolio_coin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portofolio",
            old_name="amount",
            new_name="amount_in",
        ),
        migrations.AddField(
            model_name="coininfo",
            name="updated_at",
            field=models.DateTimeField(default=api.models.default_datetime),
        ),
        migrations.AddField(
            model_name="portofolio",
            name="amount_out",
            field=models.FloatField(null=True),
        ),
    ]
