# Generated by Django 5.0.4 on 2024-05-08 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='amount_to_buy',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='configurations',
            name='slippage_rate',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='capital_coin',
            field=models.FloatField(default=5000),
        ),
        migrations.RenameModel(
            old_name='Coins',
            new_name='CoinInfo',
        ),
        migrations.CreateModel(
            name='TradePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_coin_amount', models.FloatField()),
                ('coin_amount', models.FloatField()),
                ('min_amount_out', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('execution_price', models.FloatField(blank=True, null=True)),
                ('price_impact', models.FloatField(blank=True, null=True)),
                ('is_pump_fun', models.BooleanField(default=True)),
                ('platform_fee', models.FloatField()),
                ('base_currency', models.CharField(max_length=250)),
                ('quote_currency', models.CharField(max_length=250)),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coininfo')),
            ],
        ),
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(unique=True)),
                ('txid_url', models.CharField(max_length=500, unique=True)),
                ('amount', models.FloatField()),
                ('base_amount', models.FloatField()),
                ('trade_pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tradepair')),
            ],
        ),
    ]
