# Generated by Django 5.0.4 on 2024-05-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_slippage_rate_configurations_buy_slippage_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradepair",
            name="txid",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tradepair",
            name="txid_url",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
