# Generated by Django 5.0.4 on 2024-05-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_tradepair_txid_alter_tradepair_txid_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coininfo",
            name="bought",
        ),
    ]
