# Generated by Django 5.0.4 on 2024-05-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_amount_portofolio_amount_in_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portofolio",
            old_name="amount_in",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="portofolio",
            name="amount_out",
        ),
    ]
