# Generated by Django 5.0.4 on 2024-05-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rename_amount_in_portofolio_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurations",
            name="first_wait_seconds",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="configurations",
            name="second_wait_seconds",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="configurations",
            name="third_wait_seconds",
            field=models.IntegerField(default=15),
        ),
    ]
