# Generated by Django 5.0.4 on 2024-05-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_configurations_first_wait_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradepair",
            name="holders",
            field=models.IntegerField(default=2),
        ),
    ]
