# Generated by Django 5.0.4 on 2024-05-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_tradepair_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradepair",
            name="txid",
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name="tradepair",
            name="txid_url",
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
