# Generated by Django 5.0.4 on 2024-05-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_tradepair_txid_alter_tradepair_txid_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tradepair",
            old_name="base_coin_amount",
            new_name="amount_in",
        ),
        migrations.RenameField(
            model_name="tradepair",
            old_name="coin_amount",
            new_name="amount_out",
        ),
    ]
